[versions]

compose-material3 = "1.10.0-alpha05"
compose-activity = "1.12.4"
lifecycle = "2.10.0-alpha08"
navigation = "2.9.2"
serialization = "1.10.0"
coroutines = "1.10.2"
ktor = "3.4.0"

kotlin = "2.3.10"
android = "9.0.1"
compose = "1.10.1"
compose-reload = "1.0.0"
koin-compiler = "0.3.0"

sdk-min = "24"
sdk-compile = "36"
sdk-target = "36"

[libraries]

compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
ktor = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

[plugins]

kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android = { id = "com.android.application", version.ref = "android" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-reload" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }